
name: CI

# Run tests on pull requests and when changes are directly
# commited to master.
on:
  push:
    branches: [ master ]
  pull_request:
    branches:
      - master
      # run the CI also on PRs that are based on branches starting with pr/...
      - 'pr/**'
  schedule:
    - cron: 1 1 * * *

jobs:
  # Run static/code-quality checks
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-go@v2
      with:
        go-version: 1.17
    - uses: actions/checkout@v2
    - name: golangci-lint
      uses: golangci/golangci-lint-action@v2
      with:
        # Optional: version of golangci-lint to use in form of v1.2 or v1.2.3 or `latest` to use the latest version
        version: v1.42.1

        # Optional: working directory, useful for monorepos
        # working-directory: somedir

        # Optional: golangci-lint command line arguments.
        # args: --issues-exit-code=0

        # Optional: show only new issues if it's a pull request. The default value is `false`.
        only-new-issues: yes

        # Optional: if set to true then the action will use pre-installed Go.
        skip-go-installation: true

        # Optional: if set to true then the action don't cache or restore ~/go/pkg.
        # skip-pkg-cache: true

        # Optional: if set to true then the action don't cache or restore ~/.cache/go-build.
        # skip-build-cache: true

  # Run the test suite in a container per-ceph-codename
  # test-suite:
  #   runs-on: ubuntu-latest
  #   strategy:
  #     matrix:
  #       ceph_version:
  #       - "nautilus"
  #       - "octopus"
  #       - "pacific"
  #   steps:
  #   - uses: actions/checkout@v2
  #   - name: Run tests
  #     run: make test-containers-test "CEPH_VERSION=${{ matrix.ceph_version }}" "RESULTS_DIR=$PWD/_results"
  #   - name: Run tests with ptrguard
  #     run: make test-containers-test "CEPH_VERSION=${{ matrix.ceph_version }}" "USE_PTRGUARD=true" "RESULTS_DIR=$PWD/_results"
  #   - name: Clean up test containers
  #     run: make test-containers-clean "CEPH_VERSION=${{ matrix.ceph_version }}"
  #   - name: Archive coverage results
  #     uses: actions/upload-artifact@v2
  #     with:
  #       name: "go-ceph-coverage-${{ matrix.ceph_version }}"
  #       path: "_results/coverage/go-ceph.html"
  #   - name: Archive implements results
  #     if: "matrix.ceph_version == 'pacific'"
  #     uses: actions/upload-artifact@v2
  #     with:
  #       name: "go-ceph-implements-${{ matrix.ceph_version }}"
  #       path: "_results/implements.*"
  #   - name: Check API Versions and Aging
  #     run: |
  #       if [ -f _results/implements.json ]; then
  #         ./contrib/apiage.py
  #       else
  #         echo "Skipping apiage check"
  #       fi
